### ISSUE TITLE
set is not updating the original object nor the "dug" one

### ISSUE THREAD

**Issue by cdes** [vddrift/dig-ts#1]
I don't know if I'm doing something wrong but here's a simple sandbox:

https://codesandbox.io/s/wispy-sun-wpns6

**Comment by vddrift** [comment]
Thank you for trying out dig-ts.

You should add typings to your object. In this case Tree and Node.

You can add the path as different arguments, like so:
`const digger = dig(tree, "Nodes", 0, "children", 0, "children");`

https://codesandbox.io/s/gracious-perlman-zcrlz

Both original and 'dug' object are changed.

**Comment by cdes** [comment]
Oh, so I can't supply an array? 🤔
Any thanks for the cool package.
